PRODUCT_PREMIUM_PACKAGE = "premium_package"
PRODUCT_STAGE_UNLOCK = "unlock_premium_stages"
PRODUCT_REMOVE_ADS = "remove_ads"

ENTITLEMENT_HINT_AD_REMOVAL = "hint_ad_removal"
ENTITLEMENT_BANNER_AD_REMOVAL = "banner_ad_removal"
ENTITLEMENT_STAGE_UNLOCK = "stage_unlock"

PRODUCT_ENTITLEMENTS = {
    PRODUCT_PREMIUM_PACKAGE: {
        ENTITLEMENT_HINT_AD_REMOVAL,
        ENTITLEMENT_BANNER_AD_REMOVAL,
        ENTITLEMENT_STAGE_UNLOCK,
    },
    PRODUCT_STAGE_UNLOCK: {
        ENTITLEMENT_STAGE_UNLOCK,
    },
    PRODUCT_REMOVE_ADS: {
        ENTITLEMENT_HINT_AD_REMOVAL,
        ENTITLEMENT_BANNER_AD_REMOVAL,
    },
}

ALL_PRODUCT_IDS = set(PRODUCT_ENTITLEMENTS)
ALL_ENTITLEMENTS = {
    ENTITLEMENT_HINT_AD_REMOVAL,
    ENTITLEMENT_BANNER_AD_REMOVAL,
    ENTITLEMENT_STAGE_UNLOCK,
}
