# Generated by Django 5.2.1 on 2026-01-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userentitlement",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="adevent",
            name="ad_network",
        ),
        migrations.RemoveField(
            model_name="adevent",
            name="reward_amount",
        ),
        migrations.RemoveField(
            model_name="adevent",
            name="reward_type",
        ),
        migrations.RemoveField(
            model_name="userstagehintaccess",
            name="unlock_source",
        ),
        migrations.AddField(
            model_name="adevent",
            name="transaction_id",
            field=models.CharField(default=123123, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userentitlement",
            name="entitlement_type",
            field=models.CharField(default="ad", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userstagehintaccess",
            name="ad_event",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="commerce.adevent",
            ),
        ),
        migrations.DeleteModel(
            name="PaymentEvent",
        ),
        migrations.RemoveField(
            model_name="userentitlement",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="userentitlement",
            name="type",
        ),
    ]
