# Generated by Django 5.2.1 on 2026-01-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedrefreshtoken",
            name="session_scope",
            field=models.CharField(default="local", max_length=20),
        ),
    ]
